version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
    volumes:
      - ./back/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./back/.env:/docker-entrypoint-initdb.d/.env:ro

  back:
    build:
      context: ./back
    container_name: expressjs
    restart: always

  front:
    build:
      context: ./front
    container_name: nextjs
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host({any:.*})"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
