version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=hibobo@kurama-chat.xyz"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
    networks:
      - web

  mongodb:
    image: mongo:4.2.19
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - web

  backend:
    container_name: backend
    image: node:21
    working_dir: /backend
    command: sh -c "npm install && npm rebuild bcrypt --build-from-source && npx nodemon"
    volumes:
      - ./backend:/backend
    networks:
      - web
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - ORIGIN_URL=${ORIGIN_URL}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
    ports:
      - 4000:4000

  frontend:
    container_name: frontend
    depends_on:
      - traefik
    image: node:21
    working_dir: /frontend/src
    command: sh -c 'npm install --legacy-peer-deps && npm run dev'
    volumes:
      - ./frontend:/frontend/src
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontend.rule=Host(`kurama-chat.com`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.domains[0].main=kurama-chat.com
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - web
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - BROWSER=none
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    ports:
      - 3000:3000

networks:
  web:
