version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
    volumes:
      - ./back/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./back/.env:/docker-entrypoint-initdb.d/.env:ro

  backend:
    image: node:21
    working_dir: /back/src/
    command: sh -c "npm install && npm start"
    volumes:
      - ./back:/back/src
    ports:
      - 3001:3001

  front:
    image: node:21
    working_dir: /app/src
    command: sh -c 'npm install && npm run build && npm start'
    volumes:
      - ./front:/app/src
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host({any:.*})"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
