- hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    - name: Update instance
      apt:
        name: "*"
        state: latest

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install pip
      apt:
        name: python-pip
        state: latest

    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker
      service:
        name: docker
        state: started

    - name: copy file
      copy:
        src: ./
        dest: /tmp/deployement/

    - name: Install docker-compose
      pip:
        name: docker-compose
        extra_args: --ignore-installed

    - name: Install docker-py
      pip:
        name: docker
        extra_args: --ignore-installed

    - name: Create .env file with SITE_ADDRESS
      copy:
        dest: /tmp/deployement/.env
        content: |
          MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE={{ MONGO_INITDB_DATABASE }}
          MONGODB_USER={{ MONGODB_USER }}
          MONGODB_USER_PASSWORD={{ MONGODB_USER_PASSWORD }}

    - name: Execute docker-compose for WordPress
      docker_compose:
        project_src: /tmp/deployement/
