import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./Layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>SITE ELG</title>
        {}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
