name: Build and Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format Terraform files
        run: terraform fmt

  init:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Terraform files
        run: terraform validate

  apply:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply Terraform configuration
        run: |
          terraform apply -auto-approve
          echo "hosts" > ./hosts
        env:
          TF_VAR_db_user: ${{ env.DB_USER }}
          TF_VAR_db_password: ${{ env.DB_PASSWORD }}
          TF_VAR_db_name: ${{ env.DB_NAME }}

  configure_and_deploy:
    needs: apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure & Deploy with Ansible
        run: |
          eval $(ssh-agent -s)
          chmod 400 "${SSH_PRIVATE_KEY}"
          ssh-add "${SSH_PRIVATE_KEY}"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          python3 -m pip install docker
          ansible-galaxy collection install community.docker
          ansible-playbook -i hosts playbook.yml

  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Destroy Infrastructure (Manual Trigger)
        run: terraform destroy -auto-approve
